dateModified: 1675964066
email:
  fromEmail: info@putyourlightson.net
  fromName: 'Craft Coding Challenge'
  transportType: craft\mail\transportadapters\Sendmail
graphql:
  publicToken:
    enabled: false
    expiryDate: null
meta:
  __names__:
    0d89c679-f6f5-42ae-8341-4bea917c6af7: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    5d8ac5fd-078c-48a1-b576-70061205ec38: Products # Products
    469a43c1-fde9-4ea1-a106-fc403421ba0a: Description # Description
    0779f354-f5d2-4f82-9a36-28a252f70ce4: 'Public Schema' # Public Schema
    31006d4c-2f40-498c-9a4c-69cff4fd4279: Common # Common
    b55012be-3f7f-4150-b59c-5a6623c00743: 'Public Schema' # Public Schema
    c7c2807b-84cc-4e1f-9279-af044bc0b472: 'Public Schema' # Public Schema
    d66c51fd-6d2a-4910-acf8-716ba86945f8: Images # Images
    ea74d7f8-e3fe-442e-ae8c-62bdbf83dc92: Default # Default
    f255ef6d-0c55-4bdc-9ced-f610bbb3bed6: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
plugins:
  buggy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.6
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.4.0
system:
  edition: pro
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
