name: Build Docker Images
on:
  push:
    branches:
      - develop
    paths:
      - .docker-config/spin-up-craft-base/*
  workflow_dispatch:
jobs:
  build-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1"]
    name: spin-up-craft-base ${{ matrix.php }} images
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build .docker-config/nystudio107/spin-up-craft-base:${{ matrix.php }}-alpine
        uses: docker/build-push-action@v2
        with:
          context: .docker-config/spin-up-craft-base/php-${{ matrix.php }}-alpine
          file: .docker-config/spin-up-craft-base/php-${{ matrix.php }}-alpine/Dockerfile
          push: false
          platforms: linux/amd64,linux/arm64
          tags: nystudio107/spin-up-craft-base:${{ matrix.php }}-alpine
          build-args: |
            PHP_VERSION=${{ matrix.php }}
